name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t dvwa-app .

      - name: Run Snyk Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk test --docker dvwa-app

      - name: Run StackHawk Scan
        env:
          HAWK_API_KEY: ${{ secrets.HAWK_API_KEY }}
        continue-on-error: true
        run: |
          curl -sL https://github.com/stackhawk/hawkscan-cli/releases/latest/download/hawkscan-linux-amd64.tar.gz | tar xz
          ./hawkscan

      - name: Deploy DVWA Container
        run: |
          docker stop dvwa || true
          docker rm dvwa || true
          docker run -d -p 8080:80 --name dvwa dvwa-app
